### ISSUE TITLE
Nightly test failure in DigitalOcean C# test

### ISSUE THREAD

**Issue by t0yv0** [pulumi/examples#1017]
https://pulumi.slack.com/archives/C5J0XFWRJ/p1623165970015900

```
   error: Running program
   '/tmp/p-it-fv-az399-5-digitaloce-dcc5275a-897067229/bin/Debug/netcoreapp3.1/Digitalocean.K8s.dll'
   failed with an unhandled exception: System.NullReferenceException:

   Object reference not set to an instance of an object.


   System.NullReferenceException: Object reference not set to an instance of an object.
       at Pulumi.Deployment.<>c.<GetAllTransitivelyReferencedCustomResourceURNsAsync>b__75_0(CustomResource r)
       at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
       at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1 tasks)
       at Pulumi.Deployment.GetAllTransitivelyReferencedCustomResourceURNsAsync(HashSet`1 resources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.ProviderResource.RegisterAsync(ProviderResource provider)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeDictionaryAsync(String ctx, IDictionary dictionary, Boolean keepResources)

        https://github.com/pulumi/pulumi/pull/7170/files
```

## Steps to reproduce

```
cd misc/test
go test -tags DigitalOcean -run TestAccDigitalOceanCsK8
```

**Comment by t0yv0** [comment]
Initial hypotheses were that the null is in cluster.KubeConfigs.GetAt(0) or v.RawConfig but this is not the case.

This is the function encountering the null:

```
        private static async Task<HashSet<string>> GetAllTransitivelyReferencedCustomResourceURNsAsync(
            HashSet<Resource> resources)
        {
            ...
            var tasks = transitivelyReachableCustomResources.Select(r => {
                try
                {
                    return r.Urn.GetValueAsync();
                }
                catch (Exception e)
                {
                    var nullUrn = r.Urn == null;
                    throw new Exception($"AHA! r: {r}; null r.Urn: {nullUrn}; e: {e}");
                }
            });
            ...
        }
```
 
```
    System.Exception: AHA! r: Pulumi.DigitalOcean.KubernetesCluster; null r.Urn: True; e: System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by t0yv0** [comment]
Downgrading to Pulumi 3.3.1 does not fix the issue.

Downgrading to Pulumi.DigitalOcean 4.3.1 (from 4.4.0) fixes the issue.

**Comment by t0yv0** [comment]
```
git diff v4.3.1..v4.4.0 -- sdk/dotnet/KubernetesCluster.cs
WARNING: terminal is not fully functional
-  (press RETURN)
diff --git a/sdk/dotnet/KubernetesCluster.cs b/sdk/dotnet/KubernetesCluster.cs
index 14b6b70..4e2ce27 100644
--- a/sdk/dotnet/KubernetesCluster.cs
+++ b/sdk/dotnet/KubernetesCluster.cs
@@ -102,6 +102,12 @@ namespace Pulumi.DigitalOcean
         [Output("updatedAt")]
         public Output<string> UpdatedAt { get; private set; } = null!;
 
+        /// <summary>
+        /// The uniform resource name (URN) for the Kubernetes cluster.
+        /// </summary>
+        [Output("urn")]
+        public Output<string> Urn { get; private set; } = null!;
+
         /// <summary>
         /// The slug identifier for the version of Kubernetes used for the cluster. Use [doctl](https://github.com/digitalocean/doctl) to find the available versions `doctl kubernetes options versions`. (**Note:** A cluster may only be upgraded to newer versions in-place. If the version is decreased, a new resource will be created.)
         /// </summary>
@@ -313,6 +319,12 @@ namespace Pulumi.DigitalOcean
         [Input("updatedAt")]
         public Input<string>? UpdatedAt { get; set; }
 
+        /// <summary>
+        /// The uniform resource name (URN) for the Kubernetes cluster.
+        /// </summary>
+        [Input("urn")]
+        public Input<string>? Urn { get; set; }
+
         /// <summary>
         /// The slug identifier for the version of Kubernetes used for the cluster. Use [doctl](https://github.com/digitalocean/doctl) to find the available versions `doctl kubernetes options versions`. (**Note:** A cluster may only be upgraded to newer versions in-place. If the version is decreased, a new resource will be created.)
         /// </summary>

```

**Comment by t0yv0** [comment]
It think this Pulumi concept Urn property from Resource got overwritten with inheritance accidentally with some unrelated concept Urn from DigitalOcean:

```
  
   /// <summary>
   /// Urn is the stable logical URN used to distinctly address a resource, both before and
   /// after deployments.
   /// </summary>
   // Set using reflection, so we silence the NRT warnings with `null!`.
   [Output(Constants.UrnPropertyName)]
   public Output<string> Urn { get; private protected set; } = null!;

```

To prevent this we would want to make this property sealed.

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/pulumi-digitalocean/issues/243
