### ISSUE TITLE
Error previewing update in azure-ts-aks-helm

### ISSUE THREAD

**Issue by rohancragg** [pulumi/examples#193]
_(Newbie disclaimer)_

I'm trying this example: https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm

I click on the 'Deploy with Pulumi' button and the stack gets created ok in my project.

When I attempt the `pulumi new` command 

```
pulumi new https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm -s <MyStack>
```
I get this error:

> Running program 'C:\src\pulumi\azure-ts-aks-helm-dev' failed with an unhandled exception:
> TSError: ⨯ Unable to compile TypeScript:
> index.ts(21,6): error TS2339: Property 'status' does not exist on type 'Output<Service>'.
> index.ts(21,19): error TS7006: Parameter 'status' implicitly has an 'any' type.
> 
>     at createTSError (C:\src\pulumi\azure-ts-aks-helm-dev\node_modules\ts-node\src\index.ts:261:12)
>     at getOutput (C:\src\pulumi\azure-ts-aks-helm-dev\node_modules\ts-node\src\index.ts:367:40)
>     at Object.compile (C:\src\pulumi\azure-ts-aks-helm-dev\node_modules\ts-node\src\index.ts:558:11)
>     at Module.m._compile (C:\src\pulumi\azure-ts-aks-helm-dev\node_modules\ts-node\src\index.ts:439:43)
>     at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (C:\src\pulumi\azure-ts-aks-helm-dev\node_modules\ts-node\src\index.ts:442:12)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:658:17)
> an unhandled error occurred: Program exited with non-zero exit code: 1

I'm on Windows 10 and my $PSVersionTable is:

> PSVersion                      5.1.17134.407
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.17134.407
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

Any suggestions?

Many Thanks

**Comment by rohancragg** [comment]
Thanks for the very quick fix!

I tried again and I get this fantastic user experience:

> warning: A new version of Pulumi is available. To upgrade from version '0.16.7' to '0.16.8', run
>    > powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1'))"
> or visit https://pulumi.io/install for manual instructions and release notes.

I updated my Pulumi CLI as instructed.

Ran again and my resources are now creating as we speak.

Many Thanks for a great product!
