### ISSUE TITLE
Runtime Error: index out of range for gcp-ts-gke example

### ISSUE THREAD

**Issue by jkogut** [pulumi/examples#232]
I hope resources with its versions are satisfied:
```js
pulumi plugin ls
NAME        KIND      VERSION  SIZE   INSTALLED  LAST USED
gcp         resource  0.16.7   61 MB  n/a        1 hour ago
kubernetes  resource  0.13.0   40 MB  n/a        48 minutes ago

TOTAL plugin cache size: 101 MB
```

Pulumi panics on **kubernetes:apps:Deployment** step, with **panic: runtime error: index out of range** error:

```js
[noname]:~/dev/github/pulumi/examples/gcp-ts-gke$ pulumi up

Previewing update (gcp-ts-gke-dev2):

     Type                            Name                        Plan       
     pulumi:pulumi:Stack             gcp-ts-gke-gcp-ts-gke-dev2             
 +   ├─ gcp:container:Cluster        gke-cluster                 create     
 +   ├─ pulumi:providers:kubernetes  gkeK8s                      create     
 +   └─ kubernetes:apps:Deployment   canary                      create     
 
Resources:
    + 3 to create
    1 unchanged

Do you want to perform this update? yes
Updating (gcp-ts-gke-dev2):

     Type                            Name                        Status         Info
     pulumi:pulumi:Stack             gcp-ts-gke-gcp-ts-gke-dev2                 20 messages
 +   ├─ gcp:container:Cluster        gke-cluster                 created        
 +   ├─ pulumi:providers:kubernetes  gkeK8s                      created        
     └─ kubernetes:apps:Deployment   canary                      **failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (gcp-ts-gke-gcp-ts-gke-dev2):
    panic: runtime error: index out of range
    goroutine 20 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).gvkFromURN(0xc4201e8280, 0xc4202f00c0, 0x52, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:475 +0x269
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Check(0xc4201e8280, 0x1aebac0, 0xc4202ac5a0, 0xc42041e140, 0xc4201e8280, 0x1, 0x1)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:157 +0x3f5
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x1aebac0, 0xc4202ac5a0, 0x11c0ea0, 0xc42041e140, 0x1aebac0, 0xc4202ac5a0, 0x1af0280, 0x1b6c728)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:735 +0x86
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1aebac0, 0xc4202ac5a0, 0x11c0ea0, 0xc42041e140, 0xc42041e3e0, 0xc42041e420, 0x0, 0x0, 0x1ad08c0, 0xc420299c80)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x11f4780, 0xc4201e8280, 0x1aebac0, 0xc4202ac1e0, 0xc42027a5a0, 0xc4201c77a0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:737 +0x16d
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42019aa00, 0x1aee700, 0xc4202b8580, 0xc4204b6000, 0xc420273500, 0x1b3f6b0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42019aa00, 0x1aee700, 0xc4202b8580, 0xc4204b6000, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42033e380, 0xc42019aa00, 0x1aee700, 0xc4202b8580, 0xc4204b6000)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/google.golang.org/grpc/server.go:570 +0xa1
 
  kubernetes:apps:Deployment (canary):
    error: transport is closing```

**Comment by jkogut** [comment]
Followed great [hello-gke tutorial](https://pulumi.io/quickstart/gcp/tutorial-gke.html) :+1: :1st_place_medal: and figured out my own plugin version mess. 

```js
npm install --save @pulumi/pulumi @pulumi/gcp @pulumi/kubernetes
pulumi plugin rm resource kubernetes 0.13.0
```
that did the trick: so now  `pulumi plugin ls`, gives me proper results:

```js
NAME        KIND      VERSION  SIZE   INSTALLED  LAST USED
gcp         resource  0.16.7   61 MB  n/a        3 hours ago
kubernetes  resource  0.20.1   45 MB  n/a        56 minutes ago

TOTAL plugin cache size: 106 MB
```

then finished deployment with `pulumi up`:
```js
Do you want to perform this update? yes
Updating (gcp-ts-gke-dev2):

     Type                           Name                        Status      
     pulumi:pulumi:Stack            gcp-ts-gke-gcp-ts-gke-dev2              
 +   └─ kubernetes:apps:Deployment  canary                      created     
 ```

Summary:
**[ + ]** you can still finish deployment with `pulumi` while performing nodejs upgrade (not advised).
Thank you @lukehoban for some hints :+1:
