### ISSUE TITLE
thumbnailer-rekognition  AccessDeniedException

### ISSUE THREAD

**Issue by foxundermoon** [pulumi/examples#259]
```

Collecting logs for stack thumbnailer-rekognition since 2019-03-13T17:02:41.000+08:00.

 2019-03-13T18:02:38.007+08:00[                    onNewVideo] *** New video: file cat.mp4 was uploaded at 2019-03-13T10:02:37.484Z.
 2019-03-13T18:02:42.627+08:00[                    onNewVideo] *** Submitted Rekognition job for cat.mp4
 2019-03-13T18:02:59.156+08:00[AmazonRekognitionTopic_labelRe] *** Rekognition job complete
 2019-03-13T18:03:03.417+08:00[AmazonRekognitionTopic_labelRe] { AccessDeniedException: User: arn:aws:sts::760647938248:assumed-role/AmazonRekognitionTopic_labelResults-3a251b2/AmazonRekognitionTopic_labelResults-979f14d is not authorized to perform: rekognition:GetLabelDetection
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'User: arn:aws:sts::760647938248:assumed-role/AmazonRekognitionTopic_labelResults-3a251b2/AmazonRekognitionTopic_labelResults-979f14d is not authorized to perform: rekognition:GetLabelDetection',
  code: 'AccessDeniedException',
  time: 2019-03-13T10:03:03.416Z,
  requestId: '30c8ee49-4577-11e9-9210-25507ec0ecc2',
  statusCode: 400,
  retryable: false,
  retryDelay: 13.157452204157295 } 'AccessDeniedException: User: arn:aws:sts::760647938248:assumed-role/AmazonRekognitionTopic_labelResults-3a251b2/AmazonRekognitionTopic_labelResults-979f14d is not authorized to perform: rekognition:GetLabelDetection\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'
```

**Comment by leezen** [comment]
I wasn't able to reproduce this issue with the example (I ran `pulumi up` and all the resources were instantiated correctly). I would check if the profile you're executing has the requisite permissions. Closing for now as I'm not able to reproduce.

**Comment by leezen** [comment]
Ah, sorry, I misread and I see now this is happening at the end of the example when you attempt to actually run the example. Looking into it further.

**Comment by leezen** [comment]
I found the issue and it looks like it's a bug in the pulumi-cloud package. I've submitted a PR to fix this -- https://github.com/pulumi/pulumi-cloud/pull/763
