### ISSUE TITLE
Error in azure-cs-appservice

### ISSUE THREAD

**Issue by sujithq** [pulumi/examples#476]
Trying this example https://github.com/pulumi/examples/tree/master/azure-cs-appservice, I get this error. 
`
    System.InvalidOperationException: Expected System.String but got System.Collections.Immutable.ImmutableArray`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] deserializing Pulumi.Azure.AppService.AppService.appSettings
       at Pulumi.Serialization.Converter.EnsureType[T](String context, Object val)
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertDictionary(String fieldName, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, Input`1 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, Input`1 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
`
When I ommit the AppSettings part creating an AppServiceArgs it works fine (as it will be deployed)

**Comment by mikhailshilkov** [comment]
@pgavlin @CyrusNajmabadi The error happens in [`Converter`](https://github.com/pulumi/pulumi/blob/394c91d7f6ab7a4096f4454827690a460f665433/sdk/dotnet/Pulumi/Serialization/Converter.cs#L177) when trying to serialize the following:
```
"appSettings": {
    "WEBSITE_RUN_FROM_PACKAGE": "blabla",
    "__defaults": []
},
```

What are these `__defaults`, are they new, should we ignore them while converting?

**Comment by lukehoban** [comment]
@mikhailshilkov  or @sujithq Has this always been the case for this example, or is it triggered by an upgrade to a newer `Pulumi` package or newer CLI?

**Comment by CyrusNajmabadi** [comment]
so the error seems somewhat by design.  Specifically, `AppSettings` is defined like so:

```c#
 public Output<ImmutableDictionary<string, string>> AppSettings { get; private set; } = null!;
```

As it says, this should be a dictionary of strings to strings.  but htere was an empty array returned back with everything.  In TS this is generally not a problem since all the types are prescriptive, and no one would notice unless they went specifically looking for the __defaults property.  In .net though this of course breaks things.

**Comment by CyrusNajmabadi** [comment]
i need to learn a little more about what __defaults are in order to determine what the right thing is to do here.  @pgavlin can you point me toward some info on this (or just quickly summarize it yourself).  Importantly: does the sdk need to understand tehse and somehow represent/rountrip these values?  Or is it sufficient to just ignore them entirely when we deserialize engine values?
