### ISSUE TITLE
aws-ts-url-shortener-cache-http lambda fails with Runtime.ImportModuleError

### ISSUE THREAD

**Issue by christophgysin** [pulumi/examples#514]
After deploying the example aws-ts-url-shortener-cache-http, calling the endpoint returns HTTP error code 500.

Checking the CloudWatch logs, it seems that the lambda wasn't packaged correctly:

```
2020-01-15T14:05:49.904Z        undefined       ERROR   Uncaught Exception
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '@pulumi/aws/apigateway/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "stack": [
    "Runtime.ImportModuleError: Error: Cannot find module '@pulumi/aws/apigateway/index.js'",
    "Require stack:",
    "- /var/task/__index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
    "    at Module.load (internal/modules/cjs/loader.js:812:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)",
    "    at internal/main/run_main_module.js:17:11"
  ]
}
```

**Comment by CyrusNajmabadi** [comment]
i can try to look at this today.  def a bug on our side.  we have some captured function somewhere that is pulling in a pulumi module.  we need to mark this helper as 'doNotCapture'.
