### ISSUE TITLE
aws-ts-ec2-provisioners example is broken

### ISSUE THREAD

**Issue by spara** [pulumi/examples#536]
The example can't read the secret privateKey. Also tried adding the privateKey without a secret, and that failed as well

```
Do you want to perform this update? yes
Updating (dev):

     Type                                  Name                         Status                  Info
 +   pulumi:pulumi:Stack                   aws-ts-ec2-provisioners-dev  **creating failed**     1 error; 9 messages
 +   ├─ aws:ec2:KeyPair                    key                          created
 +   ├─ aws:ec2:SecurityGroup              secgrp                       created
 +   ├─ aws:ec2:Instance                   server                       created
 +   └─ pulumi:provisioners:CopyFile       config                       created
 +      └─ pulumi-nodejs:dynamic:Resource  config-provisioner           **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (aws-ts-ec2-provisioners-dev):
    /Users/sophiaparafina/git/pulumi/examples/aws-ts-ec2-provisioners/node_modules/scp2/node_modules/ssh2/lib/client.js:146
          throw new Error('Cannot parse privateKey: ' + privKeyInfo.message);
                ^
    Error: Cannot parse privateKey: Unsupported key format
        at Client.connect (/Users/sophiaparafina/git/pulumi/examples/aws-ts-ec2-provisioners/node_modules/scp2/node_modules/ssh2/lib/client.js:146:13)
        at Client.sftp (/Users/sophiaparafina/git/pulumi/examples/aws-ts-ec2-provisioners/node_modules/scp2/lib/client.js:99:7)
        at Client.mkdir (/Users/sophiaparafina/git/pulumi/examples/aws-ts-ec2-provisioners/node_modules/scp2/lib/client.js:129:8)
        at /Users/sophiaparafina/git/pulumi/examples/aws-ts-ec2-provisioners/node_modules/scp2/lib/client.js:267:14
        at FSReqWrap.oncomplete (fs.js:154:5)

    error: update failed

  pulumi-nodejs:dynamic:Resource (config-provisioner):
    error: transport is closing

Resources:
    + 5 created

Duration: 56s

Permalink: https://app.pulumi.com/spara/aws-ts-ec2-provisioners/dev/updates/20
```

**Comment by lukehoban** [comment]
> Error: Cannot parse privateKey: Unsupported key format

What format was the private key you provided?  Did you follow the steps in README or try something else?

**Comment by spara** [comment]
I followed the steps in the README but that is also incorrect. This is the header generated from the instructions in the README:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

and this is the code in the example:

```
// The privateKey associated with the selected key must be provided (either directly or base64 encoded), along with an optional
// passphrase if needed.
const privateKey = config.requireSecret("privateKey").apply(key => {
    if (key.startsWith("-----BEGIN RSA PRIVATE KEY-----")) {
        return key;
    } else {
        return new Buffer(key, "base64").toString("ascii");
    }
});
```

**Comment by stack72** [comment]
I just tested this and it is indeed incorrect - there was a small missing part from the README which I am opening a PR right now to fix
