### ISSUE TITLE
aws-stackreference-architecture/networking broken?

### ISSUE THREAD

**Issue by viq** [pulumi/examples#544]
I'm trying to stand this up (in `eu-central-1`), and getting an error:
```
$ pulumi config
KEY          VALUE
aws:profile  sky
aws:region   eu-central-1
azCount      2
```
```
$ pulumi up
Previewing update (dev):

     Type                 Name                  Plan       Info
 +   pulumi:pulumi:Stack  networking-layet-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (networking-layet-dev):
    error: Running program '/home/user/pulumi-examples/aws-stackreference-architecture/networking' failed with an unhandled exception:
    TypeError: Cannot read property 'slice' of undefined
        at /home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:23:56
        at Generator.next (<anonymous>)
        at /home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:8:71
        at new Promise (<anonymous>)
        at __awaiter (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:4:12)
        at main (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:16:12)
        at Object.<anonymous> (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:69:18)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Module.m._compile (/home/user/pulumi-examples/aws-stackreference-architecture/networking/node_modules/ts-node/src/index.ts:536:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 
```

It sounds like maybe it's not able to get the availability zones? But I'm able to from cli:
```
$ aws --profile sky ec2 describe-availability-zones
{
    "AvailabilityZones": [
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1a",
            "ZoneId": "euc1-az2"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1b",
            "ZoneId": "euc1-az3"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "eu-central-1",
            "ZoneName": "eu-central-1c",
            "ZoneId": "euc1-az1"
        }
    ]
}
```
Sorry, I'm not sure what other information to provide that would be useful here.

**Comment by viq** [comment]
For what it's worth, some debug output:
```
$ pulumi up -d -v=5
Previewing update (dev):

     Type                 Name                  Plan       Info
 +   pulumi:pulumi:Stack  networking-layer-dev  create     1 error; 26 debugs
 
Diagnostics:
  pulumi:pulumi:Stack (networking-layer-dev):
    debug: Registering resource: t=pulumi:pulumi:Stack, name=networking-layer-dev, custom=false
    debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=networking-layer-dev
    debug: RegisterResource RPC finished: resource:networking-layer-dev[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:dev::networking-layer::pulumi:pulumi:Stack::networking-layer-dev,,,,
    debug: Running program '/home/user/pulumi-examples/aws-stackreference-architecture/networking' in pwd '/home/user/pulumi-examples/aws-stackreference-architecture/networking' w/ args: 
    debug: Invoking function: tok=aws:index/getAvailabilityZones:getAvailabilityZones asynchronously
    debug: , obj={"state":"available"}
    debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:dev::networking-layer::pulumi:pulumi:Stack::networking-layer-dev
    error: Running program '/home/user/pulumi-examples/aws-stackreference-architecture/networking' failed with an unhandled exception:
    TypeError: Cannot read property 'slice' of undefined
        at /home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:23:56
        at Generator.next (<anonymous>)
        at /home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:8:71
        at new Promise (<anonymous>)
        at __awaiter (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:4:12)
        at main (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:16:12)
        at Object.<anonymous> (/home/user/pulumi-examples/aws-stackreference-architecture/networking/src/index.ts:69:18)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Module.m._compile (/home/user/pulumi-examples/aws-stackreference-architecture/networking/node_modules/ts-node/src/index.ts:536:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    debug: Setting AWS metadata API timeout to 100ms
    debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:dev::networking-layer::pulumi:pulumi:Stack::networking-layer-dev; err: null, resp: 
    debug: Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
    debug: AWS Auth provider used: "SharedCredentialsProvider"
    debug: No assume_role block read from configuration
    debug: Building AWS auth structure
    debug: Setting AWS metadata API timeout to 100ms
    debug: Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
    debug: AWS Auth provider used: "SharedCredentialsProvider"
    debug: Trying to get account information via sts:GetCallerIdentity
    debug: Trying to get account information via sts:GetCallerIdentity
    debug: Reading Availability Zones.
    debug: Reading Availability Zones: {
    debug:   Filters: [{
    debug:       Name: "state",
    debug:       Values: ["available"]
    debug:     }]
    debug: }
    debug: Invoke RPC finished: tok=aws:index/getAvailabilityZones:getAvailabilityZones; err: null, resp: id,,,2020-02-08 16:45:03.622252849 +0000 UTC,names,,,,,,,,eu-central-1a,,,eu-central-1b,,,eu-central-1c,state,,,available,zoneIds,,,,,,,,euc1-az2,,,euc1-az3,,,euc1-az1,
```

**Comment by viq** [comment]
On a hunch I removed `async` in https://github.com/pulumi/examples/blob/master/aws-stackreference-architecture/networking/src/index.ts#L16 and it seems to work that way - at least I get some output and suggested changes, I didn't try applying anything yet.

**Comment by viq** [comment]
Yeah, the changes got applied, and are now getting removed.
