### ISSUE TITLE
TypeScript compiling errors when using provisioners example

### ISSUE THREAD

**Issue by rrhg** [pulumi/examples#545]
Implementing the exact same functionality of aws-ts-ec2-provisioners but for a digitalocean droplet, after `pulumi up` , I get the TypeScript compiler errors posted below.  

If edit the file tsconfig.json & set `"strict": false` , it works perfect.

Research suggest that it could be fix by creating .d.ts files, BUT is very likely that I could be doing something wrong.

scp2 certainly needs a .d.ts file since @types/scp2 is non existent. But the fact that provisioners/index.ts also need type definitions , makes me wonder if is a bug or maybe the  README.md should have a mention about that. 

```
    TSError: ⨯ Unable to compile TypeScript:
    provisioners/index.ts(4,23): error TS7016: Could not find a declaration file for module 'scp2'. '/root/pulumi-infra/node_modules/scp2/index.js' implicitly has an 'any' type.
      Try `npm install @types/scp2` if it exists or add a new declaration (.d.ts) file containing `declare module 'scp2';`
    provisioners/index.ts(49,18): error TS7006: Parameter 'err' implicitly has an 'any' type.
    provisioners/index.ts(107,41): error TS7006: Parameter 'code' implicitly has an 'any' type.
    provisioners/index.ts(107,47): error TS7006: Parameter 'signal' implicitly has an 'any' type.
    provisioners/index.ts(114,36): error TS7006: Parameter 'data' implicitly has an 'any' type.
    provisioners/index.ts(194,63): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
      Type 'undefined' is not assignable to type 'string'.
    
        at createTSError (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:293:12)
        at reportTSError (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:297:19)
        at getOutput (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:399:34)
        at Object.compile (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:457:32)
        at Module.m._compile (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:536:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
        at Object.require.extensions.<computed> [as .ts] (/root/pulumi-infra/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:539:12)
        at Module.load (internal/modules/cjs/loader.js:1000:32)
        at Function.Module._load (internal/modules/cjs/loader.js:899:14)
        at Module.require (internal/modules/cjs/loader.js:1040:19)
```

**Comment by praneetloke** [comment]
@rrhg It looks like you may have `noImplicitAny` in your `tsconfig.json` somewhere in your project. That's why the TS compiler complains about it.  If you need that setting to be true for other files in your project, you can add a `tsconfig.json` that extends your root `tsconfig.json` in the folder where you have your Pulumi app and set it to `false`.

**Comment by rrhg** [comment]
Ok, thanks.
