### ISSUE TITLE
Python example  azure-py-functions-raw seems broken

### ISSUE THREAD

**Issue by nickvdyck** [pulumi/examples#585]
When I initially created my `venv` and installed all requirements these were the dependencies that pip resolved:

- pulumi-1.11.1
- pulumi-azure-1.14.0

If I run pulumi up I get the following stack trace:
```sh
λ pulumi up
Previewing update (test):
     Type                         Name                         Plan       Info
 +   pulumi:pulumi:Stack          azure-py-functions-raw-test  create     3 errors
 +   ├─ azure:core:ResourceGroup  windowsrg                    create
 +   ├─ azure:storage:Account     httpdotnet                   create
 +   ├─ azure:storage:Container   http-dotnet                  create
 +   └─ azure:storage:ZipBlob     http-dotnet                  create     1 warning

Diagnostics:
  azure:storage:ZipBlob (http-dotnet):
    warning: urn:pulumi:test::azure-py-functions-raw::azure:storage/zipBlob:ZipBlob::http-dotnet verification warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider

  pulumi:pulumi:Stack (azure-py-functions-raw-test):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Users/nickvd/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
        return future.result()
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 54, in run_in_stack
        await RPC_MANAGER.rpcs.pop()
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
        Stack(func)
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 100, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Users/nickvd/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 279, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/Users/nickvd/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 30, in <module>
        account_sas=storage.get_account_sas(
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi_azure/storage/get_account_sas.py", line 122, in get_account_sas
        __ret__ = pulumi.runtime.invoke('azure:storage/getAccountSAS:getAccountSAS', __args__, opts=opts).value
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 185, in invoke
        return InvokeResult(_sync_await(asyncio.ensure_future(do_rpc())))
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 101, in _sync_await
        return fut.result()
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 182, in do_rpc
        raise exn
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/nickvd/Sources/examples/azure-py-functions-raw/venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 171, in do_invoke
        raise Exception(f"invoke of {tok} failed: {resp.failures[0].reason} ({resp.failures[0].property})")
    Exception: invoke of azure:storage/getAccountSAS:getAccountSAS failed: "connection_string": required field is not set ()
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

After that I tried pinning the version to the following:
- pulumi-1.0.0
- pulumi-azure-1.0.0

But still resulted in the same error.

I'm currently using python `3.8.0`, haven't tried a different version though as I didn't think it would be related to python version.

**Comment by mikhailshilkov** [comment]
@nickvdyck thanks for reporting! I opened #586 to fix the issue, feel free to go forward with the code there.

**Comment by nickvdyck** [comment]
Worked like a charm. Thanks for the quick reply and fix 🙌
