### ISSUE TITLE
azure-ts-aks-helm example fails

### ISSUE THREAD

**Issue by winjer** [pulumi/examples#795]
Deploying this: https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm

as per the README, does this:

```
     Type                 Name                   Plan       Info
 +   pulumi:pulumi:Stack  azure-ts-aks-helm-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (azure-ts-aks-helm-dev):
    error: Running program '/home/doug/projects/examples/azure-ts-aks-helm' failed with an unhandled exception:
    TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/kustomize.ts:79:37)
        at Module._compile (internal/modules/cjs/loader.js:1176:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
        at Module.load (internal/modules/cjs/loader.js:1040:32)
        at Function.Module._load (internal/modules/cjs/loader.js:929:14)
        at Module.require (internal/modules/cjs/loader.js:1080:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/index.ts:5:1)
        at Module._compile (internal/modules/cjs/loader.js:1176:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
```

Any hints?

**Comment by winjer** [comment]
Looks like the issue is in `helm.v2.Chart`

**Comment by stack72** [comment]
Hi @winjer 

Please can you tell me the version of Pulumi CLI you are running? I don't get the same failure - I get a failure around the output 👍 

I am trying to fix that now

Paul

**Comment by winjer** [comment]
v2.10.0

**Comment by stack72** [comment]
Hey @lblackstone any thoughts on what we can do with this example?

**Comment by lblackstone** [comment]
From the provided stack trace, it looks like you might be linking in the wrong `node_modules` or something?

```
at Object.<anonymous> (/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/kustomize.ts:79:37)
```
This is referencing kustomize, which shouldn't be part of this example.

**Comment by winjer** [comment]
Indeed, I was surprised by that myself.

I repeated this on an empty checkout of the example, and the file referenced in that stack trace does not exist:

```
Diagnostics:
  pulumi:pulumi:Stack (azure-ts-aks-helm-dev):
    error: Running program '/home/doug/projects/examples/azure-ts-aks-helm' failed with an unhandled exception:
    TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/kustomize.ts:79:37)
        at Module._compile (internal/modules/cjs/loader.js:1176:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
        at Module.load (internal/modules/cjs/loader.js:1040:32)
        at Function.Module._load (internal/modules/cjs/loader.js:929:14)
        at Module.require (internal/modules/cjs/loader.js:1080:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/index.ts:5:1)
        at Module._compile (internal/modules/cjs/loader.js:1176:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
 

doug@STILTON:~/projects/examples/azure-ts-aks-helm$ ls -l /home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/kustomize.ts
ls: cannot access '/home/doug/projects/examples/azure-ts-aks-helm/node_modules/@pulumi/kustomize/kustomize.ts': No such file or directory```

I have no idea how that can happen, I presumed you are doing some Serious Magic.

**Comment by mkoertgen** [comment]
Adjusting the import and using helm3 seems to help, i.e.

```
import * as k8s from "@pulumi/kubernetes";
...
const apache = new k8s.helm.v3.Chart(...
```
