### ISSUE TITLE
classic-azure-ts-aks-helm failing during pulumi up

### ISSUE THREAD

**Issue by t0yv0** [pulumi/examples#938]
Failing to `pulumi up` in classic-azure-ts-aks-helm.

## Expected behavior

Helm chart installed and stood up in the K8S cluster.

## Current behavior

Errors as follows:

```
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    unhandled rejection: CONTEXT(968): Invoking function: tok=kubernetes:helm:template asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

    error: Running program '/Users/anton/examples/classic-azure-ts-aks-helm' failed with an unhandled exception:
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart:
        failed to pull chart: chart "bitnami/apache" version "1.0.0" not found in
        https://charts.bitnami.com/bitnami repository
        at Object.callback (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33)
        at Object.onReceiveStatus (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@grpc/grpc-js/src/client.ts:334:26)
        at Object.onReceiveStatus (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/anton/examples/classic-azure-ts-aks-helm/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

    (node:28555) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
    (node:28555) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)

```

## Steps to reproduce

Follow instructions and `pulumi up`.

## Context (Environment)

I assumed maybe chart version bit-rotted. Here is what I currently observe in the bitnami repo:

```
helm search repo apache
helm search repo apache
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/apache          	8.3.2        	2.4.46     	Chart for Apache HTTP Server                      
bitnami/airflow         	8.0.7        	2.0.1      	Apache Airflow is a platform to programmaticall...
bitnami/cassandra       	7.4.0        	3.11.10    	Apache Cassandra is a free and open-source dist...
bitnami/kafka           	12.10.0      	2.7.0      	Apache Kafka is a distributed streaming platform. 
bitnami/solr            	0.2.3        	8.8.1      	Apache Solr is an open source enterprise search...
bitnami/tomcat          	8.2.4        	9.0.43     	Chart for Apache Tomcat                           
bitnami/dataplatform-bp1	0.2.0        	1.0.0      	OCTO Data platform Kafka-Spark-Solr Helm Chart    
bitnami/spark           	5.3.1        	3.1.1      	Spark is a fast and general-purpose cluster com...
```

I have tried editing "version" field to 8.3.2 or 2.4.26 but getting the same error.

## Affected feature

Not sure.

**Comment by t0yv0** [comment]
Should resolve with the two PRs above
